"""Provider-neutral runtime contracts and built-in adapters."""

from nico_agent.runtime.completion_gate import (
    CompletionGateFacts,
    CompletionGatePolicy,
    CompletionGateVerdict,
    evaluate_final_action,
)
from nico_agent.runtime.contracts import (
    AgentAction,
    AgentActionBatch,
    AgentActionKind,
    AgentRuntimeProvider,
    AgentRuntimeProviderV2,
    AskUserAction,
    ContextSeed,
    FinalAction,
    RuntimeCapability,
    RuntimeEvent,
    RuntimeEventType,
    RuntimeExecutionMode,
    RuntimeOutcome,
    RuntimeProviderDescriptor,
    RuntimeResult,
    RuntimeServices,
    RuntimeSessionHandle,
    RuntimeSessionRequest,
    RuntimeSessionStatus,
    RuntimeToolHandler,
    RuntimeToolIntent,
    RuntimeToolOutcome,
    RuntimeToolSession,
    RuntimeToolSpec,
    RuntimeTrajectory,
    ToolCallAction,
)
from nico_agent.runtime.hermes import HermesRuntimeProvider
from nico_agent.runtime.mock import MockRuntimeProvider
from nico_agent.runtime.native import NicoNativeRuntimeProvider
from nico_agent.runtime.registry import RuntimeProviderRegistry

__all__ = [
    "AgentAction",
    "AgentActionBatch",
    "AgentActionKind",
    "AgentRuntimeProvider",
    "AgentRuntimeProviderV2",
    "AskUserAction",
    "ContextSeed",
    "CompletionGateFacts",
    "CompletionGatePolicy",
    "CompletionGateVerdict",
    "FinalAction",
    "MockRuntimeProvider",
    "HermesRuntimeProvider",
    "NicoNativeRuntimeProvider",
    "RuntimeCapability",
    "RuntimeEvent",
    "RuntimeEventType",
    "RuntimeExecutionMode",
    "RuntimeOutcome",
    "RuntimeProviderDescriptor",
    "RuntimeProviderRegistry",
    "RuntimeResult",
    "RuntimeSessionHandle",
    "RuntimeSessionRequest",
    "RuntimeSessionStatus",
    "RuntimeTrajectory",
    "RuntimeServices",
    "RuntimeToolHandler",
    "RuntimeToolIntent",
    "RuntimeToolOutcome",
    "RuntimeToolSession",
    "RuntimeToolSpec",
    "ToolCallAction",
    "evaluate_final_action",
]
